adamcardoso/vemser-trabalho-final

src/main/java/br/com/dbc/vemser/notifica/repository/DenunciaRepository.java, src/main/java/br/com/dbc/vemser/notifica/service/DenunciaService.java
arrumei alguns aspectos em service e repo de denuncia
=> fix: denuncia criar service e repository

src/main/java/br/com/dbc/vemser/notifica/controller/LoginController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/IDenunciaController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/ILoginController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/IUsuarioController.java, src/main/java/br/com/dbc/vemser/notifica/dto/denuncia/DenunciaCreateDTO.java, src/main/java/br/com/dbc/vemser/notifica/dto/denuncia/DenunciaDTO.java, src/main/java/br/com/dbc/vemser/notifica/dto/usuario/UsuarioCreateDTO.java, src/main/java/br/com/dbc/vemser/notifica/dto/usuario/UsuarioLoginDTO.java, src/main/java/br/com/dbc/vemser/notifica/entity/Denuncia.java, src/main/java/br/com/dbc/vemser/notifica/exceptions/ErrorResponse.java, src/main/java/br/com/dbc/vemser/notifica/repository/AdminRepository.java, src/main/java/br/com/dbc/vemser/notifica/repository/DenunciaRepository.java, src/main/java/br/com/dbc/vemser/notifica/service/DenunciaService.java, src/main/resources/application.properties
melhorei a documentação da forma que o QA indicou
=> fix: melhorando documentação do login, denuncia e cadastro usuario

src/main/java/br/com/dbc/vemser/notifica/controller/DenunciaController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/IDenunciaController.java, src/main/java/br/com/dbc/vemser/notifica/repository/LoginRepository.java, src/main/java/br/com/dbc/vemser/notifica/service/DenunciaService.java
Arrumei a reutilização de alguns retornos de erro como o Leonardo deu ideia
Adicionei retornos de listas
=> fix: regra de negocio e reutilização de metodos

src/main/java/br/com/dbc/vemser/notifica/controller/DenunciaController.java, src/main/java/br/com/dbc/vemser/notifica/controller/EstatisticaController.java, src/main/java/br/com/dbc/vemser/notifica/controller/FeedController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/IDenunciaController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/IFeedController.java, src/main/java/br/com/dbc/vemser/notifica/dto/estatistica/EstatisticaDTO.java, src/main/java/br/com/dbc/vemser/notifica/entity/Estatistica.java, src/main/java/br/com/dbc/vemser/notifica/repository/EstatisticaRepository.java, src/main/java/br/com/dbc/vemser/notifica/service/DenunciaService.java, src/main/java/br/com/dbc/vemser/notifica/service/EstatisticaService.java, src/main/java/br/com/dbc/vemser/notifica/service/FeedService.java
Criei classe Feed, para retirar a listagem de todas denuncias da Classe Denuncia, não sei se é util, mas facilita no entendimento, ja q a lista de todas denuncias so vai ser vista no feed
=> add: classe feed que lista todas denuncias

src/main/java/br/com/dbc/vemser/notifica/controller/EstatisticaController.java, src/main/java/br/com/dbc/vemser/notifica/controller/FeedController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/IFeedController.java, src/main/java/br/com/dbc/vemser/notifica/dto/comentario/ComentarioDTO.java, src/main/java/br/com/dbc/vemser/notifica/dto/denuncia/DenunciaDTO.java, src/main/java/br/com/dbc/vemser/notifica/dto/usuario/UsuarioDTO.java, src/main/java/br/com/dbc/vemser/notifica/entity/Comentario.java, src/main/java/br/com/dbc/vemser/notifica/entity/Denuncia.java, src/main/java/br/com/dbc/vemser/notifica/entity/Localizacao.java, src/main/java/br/com/dbc/vemser/notifica/entity/Usuario.java, src/main/java/br/com/dbc/vemser/notifica/repository/EstatisticaRepository.java, src/main/java/br/com/dbc/vemser/notifica/service/EstatisticaService.java, src/main/java/br/com/dbc/vemser/notifica/service/FeedService.java
adicionei novos endpoints no feed, vem denuncia com comentarios e ver todas denuncias com todos comentarios
=> fix: arrumei o feed e adicionei novos endpoints

src/main/java/br/com/dbc/vemser/notifica/controller/AdminController.java, src/main/java/br/com/dbc/vemser/notifica/controller/UsuarioController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/IAdminController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/IUsuarioController.java
Documentação usuario e usuario-admin
=> feat: documentacao e ajuste valid em  usuario e usuario-admin

src/main/java/br/com/dbc/vemser/notifica/controller/CurtidaController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/ICurtidaController.java, src/main/java/br/com/dbc/vemser/notifica/entity/Curtida.java, src/main/java/br/com/dbc/vemser/notifica/entity/Denuncia.java, src/main/java/br/com/dbc/vemser/notifica/repository/ICurtidaRepository.java, src/main/java/br/com/dbc/vemser/notifica/service/CurtidaService.java, src/main/java/br/com/dbc/vemser/notifica/service/DenunciaService.java, src/main/java/br/com/dbc/vemser/notifica/service/interfaces/ICurtidaService.java
[https://www.notion.so/f9cf6843b00f461ca663e7374c6dd1ca?v=6d13d94adc9941d4bb75738199694000&p=cd47bdff88d34396aea0ba4cb7c50d53&pm=s](url)
=> Adicionar funcionalidade de curtida em Denúncia

src/main/java/br/com/dbc/vemser/notifica/controller/EnderecoController.java, src/main/java/br/com/dbc/vemser/notifica/dto/endereco/EnderecoCreateDTO.java, src/main/java/br/com/dbc/vemser/notifica/dto/endereco/EnderecoDTO.java, src/main/java/br/com/dbc/vemser/notifica/entity/Endereco.java, src/main/java/br/com/dbc/vemser/notifica/repository/IEnderecoRepository.java, src/main/java/br/com/dbc/vemser/notifica/service/EnderecoService.java
Listagem by id Usuario, Create e Update não funcionavam, passei o pedido do body para a url e parou de dar o erro de "id null"
Troquei no banco pro logradouro poder ser null, para a busca de cep funcionar para cidades pequenas q n tem logradouro conectado ao cep.
testes em todas requests bombando, falta arrumar documentação.
=> fix: request de update e create + list by id usuario n funcionavam

src/main/java/br/com/dbc/vemser/notifica/NotificaApplication.java, src/main/java/br/com/dbc/vemser/notifica/controller/RelatorioUsuarioController.java, src/main/java/br/com/dbc/vemser/notifica/dto/denuncia/DenunciaCreateDTO.java, src/main/java/br/com/dbc/vemser/notifica/dto/denuncia/DenunciaDTO.java, src/main/java/br/com/dbc/vemser/notifica/dto/feed/FeedDenunciasDto.java, src/main/java/br/com/dbc/vemser/notifica/dto/usuario/UsuarioDTO.java, src/main/java/br/com/dbc/vemser/notifica/entity/Comentario.java, src/main/java/br/com/dbc/vemser/notifica/entity/Denuncia.java, src/main/java/br/com/dbc/vemser/notifica/entity/Usuario.java, src/main/java/br/com/dbc/vemser/notifica/repository/IComentarioRepository.java, src/main/java/br/com/dbc/vemser/notifica/repository/ICurtidaRepository.java, src/main/java/br/com/dbc/vemser/notifica/repository/IRelatorioUsuarioRepository.java, src/main/java/br/com/dbc/vemser/notifica/service/DenunciaService.java, src/main/java/br/com/dbc/vemser/notifica/service/FeedService.java, src/main/java/br/com/dbc/vemser/notifica/service/RelatorioUsuarioService.java
Arrumei o bug do Usuario desacoplando da denuncia apos ela ser anonima e bugando o editar e excluir
=> fix: bug do usuario null cncelando ligação com denuncia

src/main/java/br/com/dbc/vemser/notifica/controller/AdminController.java, src/main/java/br/com/dbc/vemser/notifica/controller/ComentarioController.java, src/main/java/br/com/dbc/vemser/notifica/controller/DenunciaController.java, src/main/java/br/com/dbc/vemser/notifica/controller/EnderecoController.java, src/main/java/br/com/dbc/vemser/notifica/controller/LoginController.java, src/main/java/br/com/dbc/vemser/notifica/controller/UsuarioController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/IDenunciaController.java
=> ajustes nas controllers

src/main/java/br/com/dbc/vemser/notifica/dto/usuario/UsuarioAllDTO.java, src/main/java/br/com/dbc/vemser/notifica/entity/Comentario.java, src/main/java/br/com/dbc/vemser/notifica/entity/Curtida.java, src/main/java/br/com/dbc/vemser/notifica/entity/Denuncia.java, src/main/java/br/com/dbc/vemser/notifica/entity/Endereco.java, src/main/java/br/com/dbc/vemser/notifica/entity/Localizacao.java, src/main/java/br/com/dbc/vemser/notifica/service/EnderecoService.java
=> ajuste entitys do projeto

pom.xml, src/main/java/br/com/dbc/vemser/notifica/config/OpenApiConfig.java, src/main/java/br/com/dbc/vemser/notifica/controller/LoginController.java, src/main/java/br/com/dbc/vemser/notifica/controller/UsuarioController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/ILoginController.java, src/main/java/br/com/dbc/vemser/notifica/entity/Usuario.java, src/main/java/br/com/dbc/vemser/notifica/repository/IRelatorioUsuarioRepository.java, src/main/java/br/com/dbc/vemser/notifica/repository/LoginRepository.java, src/main/java/br/com/dbc/vemser/notifica/security/AuthenticationService.java, src/main/java/br/com/dbc/vemser/notifica/security/SecurityConfiguration.java, src/main/java/br/com/dbc/vemser/notifica/security/TokenAuthenticationFilter.java, src/main/java/br/com/dbc/vemser/notifica/security/TokenService.java, src/main/java/br/com/dbc/vemser/notifica/service/LoginService.java, src/main/java/br/com/dbc/vemser/notifica/service/UsuarioService.java, src/main/resources/application.properties
Implementei Spring Security com Login Rodando e Permissões(falta apenas setar corretamente no SecurityConfig, ja setei q o admin tem acesso a todas /**)
=> add: spring secutiry com login e permissoes com enum

src/main/java/br/com/dbc/vemser/notifica/controller/AdminController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/IAdminController.java, src/main/java/br/com/dbc/vemser/notifica/entity/Usuario.java, src/main/java/br/com/dbc/vemser/notifica/entity/enums/UsuarioAtivo.java, src/main/java/br/com/dbc/vemser/notifica/service/AdminService.java
Adicionei no Banco em Usuário o atributo Ativo CHAR(1), criei o enum no código e coloquei em pratica no listar usuarios ativos e inativos na controller admin, testei e esta rodando corretamente apenas ativos ou inativos
Utilizei o Status denuncia FECHADO como filtro na listagem, pra retornar tds denuncias diferentes dessa
falta implementar a exclusao como um Put q define o status como FECHADO(4)
=> add: logica no admin list usuario e denuncias ativo/inativo

src/main/java/br/com/dbc/vemser/notifica/controller/AdminController.java, src/main/java/br/com/dbc/vemser/notifica/controller/LoginController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/ILoginController.java, src/main/java/br/com/dbc/vemser/notifica/dto/instituicao/InstitucaoCreateDTO.java, src/main/java/br/com/dbc/vemser/notifica/dto/instituicao/InstituicaoDTO.java, src/main/java/br/com/dbc/vemser/notifica/repository/AdminRepository.java, src/main/java/br/com/dbc/vemser/notifica/service/AdminService.java, src/main/java/br/com/dbc/vemser/notifica/service/DenunciaService.java, src/main/java/br/com/dbc/vemser/notifica/service/LoginService.java
ajuste do cadastro de Login
criação do criar instituicao
teste de admin, denuncia, comentario e like
=> cadastro para service, cadastro instituicao e teste

src/main/java/br/com/dbc/vemser/notifica/controller/LoginController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/ILoginController.java, src/main/java/br/com/dbc/vemser/notifica/dto/denuncia/DenunciaDTO.java, src/main/java/br/com/dbc/vemser/notifica/dto/usuario/UsuarioCreateDTO.java, src/main/java/br/com/dbc/vemser/notifica/service/AvisosService.java, src/main/java/br/com/dbc/vemser/notifica/service/FeedService.java, src/main/java/br/com/dbc/vemser/notifica/service/LoginService.java
Arrumei os dtos pedidos, curtida esta sem dto e sem interface swagger
curtida funcionando, like e deslike
login arrumado os estouros q foram retirados
n consegui colocar novamente a criação de endereço junto então ignorei o DTO
=> fix: dtos e estouros no login

src/main/java/br/com/dbc/vemser/notifica/controller/AvisosController.java, src/main/java/br/com/dbc/vemser/notifica/controller/FeedController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/IAvisosController.java, src/main/java/br/com/dbc/vemser/notifica/controller/documentacao/IFeedController.java, src/main/java/br/com/dbc/vemser/notifica/dto/avisos/AvisosCreateDTO.java, src/main/java/br/com/dbc/vemser/notifica/dto/avisos/AvisosDTO.java, src/main/java/br/com/dbc/vemser/notifica/dto/usuario/UsuarioCreateDTO.java, src/main/java/br/com/dbc/vemser/notifica/entity/Avisos.java, src/main/java/br/com/dbc/vemser/notifica/service/AvisosService.java, src/main/java/br/com/dbc/vemser/notifica/service/EmailService.java, src/main/java/br/com/dbc/vemser/notifica/service/FeedService.java, src/main/java/br/com/dbc/vemser/notifica/service/LoginService.java, src/test/java/br/com/dbc/vemser/notifica/service/AvisosServiceTest.java, src/test/java/br/com/dbc/vemser/notifica/service/EstatisticaServiceTest.java, src/test/java/br/com/dbc/vemser/notifica/service/FeedServiceTest.java, src/test/java/br/com/dbc/vemser/notifica/service/LoginServiceTest.java
Adicionei os testes da Classe Avisos, ficou em 68% pois não testo o envio de email ao criar
=> add: Avisos Test 68% line sem testar envio de email

src/main/java/br/com/dbc/vemser/notifica/repository/UsuarioRepository.java, src/main/java/br/com/dbc/vemser/notifica/service/FeedService.java, src/main/java/br/com/dbc/vemser/notifica/service/LoginService.java, src/test/java/br/com/dbc/vemser/notifica/service/AvisosServiceTest.java, src/test/java/br/com/dbc/vemser/notifica/service/EstatisticaServiceTest.java, src/test/java/br/com/dbc/vemser/notifica/service/FeedServiceTest.java, src/test/java/br/com/dbc/vemser/notifica/service/LoginServiceTest.java
Adicionei os testes para a classe Login, está 100%, acredito q está certo
=> add: Login Test 100% line

src/main/java/br/com/dbc/vemser/notifica/service/DenunciaService.java, src/test/java/br/com/dbc/vemser/notifica/service/DenunciaServiceTest.java, src/test/java/br/com/dbc/vemser/notifica/service/LoginServiceTest.java
Adicionei os testes de denuncia, está 96%, pretendo aumentar para 100% amanha
=> add: Denuncia Test 96% line

pom.xml, src/main/java/br/com/dbc/vemser/notifica/entity/CreateRegistros.java, src/main/java/br/com/dbc/vemser/notifica/entity/LogRegistros.java, src/main/resources/application.properties
Criei as duas Entidades para MongoDB
=> add: 2 entidades em MongoDB

src/main/java/br/com/dbc/vemser/notifica/controller/CreateRegistrosController.java, src/main/java/br/com/dbc/vemser/notifica/entity/CreateRegistros.java, src/main/java/br/com/dbc/vemser/notifica/entity/LogRegistros.java, src/main/java/br/com/dbc/vemser/notifica/repository/CreateRegistrosRepository.java, src/main/java/br/com/dbc/vemser/notifica/security/SecurityConfiguration.java, src/main/java/br/com/dbc/vemser/notifica/service/CreateRegistrosService.java, src/main/java/br/com/dbc/vemser/notifica/service/LoginService.java
Criei a Controller, Service e Repository da Classe
Chamei ao fazer cadastro
=> add: classe CreateRegistros com MongoDB
